name: "Nagini Github Actions"

on:
  push:
    branches:
      - master
      - develop
      - setup-ci

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd server && npm install
     - name: "Create .netrc for Heroku Auth"
        uses: akhileshns/heroku-deploy@v3.5.7 
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} 
          heroku_app_name: "api-nagini" 
          heroku_email: "imrans110@hotmail.com" 
          path: ./server
