name: "Nagini Github Actions"

on:
  push:
    branches:
      - master
      - develop
      - setup-ci

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd server && npm install
      - name: Build
        run: cd server && npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: server-build
          path: ./server/build
