name: "Nagini Github Actions"

on:
  push:
    branches:
      - master
      - develop
      - setup-ci

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd server && npm install
      - name: "Create .netrc for Heroku Auth"
        uses: akhileshns/heroku-deploy@v3.5.7 # This is the action we are importing
        with: # It accepts some arguments to work, we can pass the argument using `with`
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # This is the same as the auth key we generated earlier
          heroku_app_name: "api-nagini" #Must be unique in Heroku
          heroku_email: "imrans110@hotmail.com" # Email attached to the account
          appdir: "server"
  build-client:
    name: Build WebClient
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd webclient && npm install
      - name: Create Build
        run: cd webclient && npm run build
      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./webclient/build"
